name: tictactoe_game
description: A new Flutter project.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  bloc: ^8.1.2
  cloud_firestore: ^4.14.0
  dartz: ^0.10.1
  equatable: ^2.0.5
  firebase_auth: ^4.16.0
  firebase_core: ^2.24.2
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  get_it: ^7.6.6
  go_router: ^13.0.1
  json_annotation: ^4.8.1
  json_serializable: ^6.7.1
  provider: ^6.1.1
  rxdart: ^0.27.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  test: ^1.24.3
  build_runner: ^2.4.7
  mocktail: ^1.0.2
  bloc_test: ^9.1.5
  fake_cloud_firestore: ^2.4.7

flutter:
  uses-material-design: true
